# Generated by Django 5.2 on 2025-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_recordtype_record_record_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(max_length=100),
        ),
    ]
