# Generated by Django 5.2 on 2025-05-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_budget_created_at_budget_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
